version: '3.8'

services:
  api1:
    build:
      context: ./api1 # Path to api1 directory
      dockerfile: Dockerfile # Default Dockerfile name, will be created implicitly
    container_name: api1_service
    ports:
      - "5000:5000" # Maps host port 5000 to container port 5000
    environment:
      - PORT=5000
      - API2_URL=http://api2:5001/analyze # Service name 'api2' and its internal port
      - AIFORTHAI_SUMMARIZE_API_KEY=${AIFORTHAI_SUMMARIZE_API_KEY} # From .env
    depends_on:
      - api2
    restart: always

  api2:
    build:
      context: ./api2 # Path to api2 directory
      dockerfile: Dockerfile # Default Dockerfile name, will be created implicitly
    container_name: api2_service
    ports:
      - "5001:5001" # Maps host port 5001 to container port 5001
    environment:
      - PORT=5001
      - AIFORTHAI_SSENSE_API_KEY=${AIFORTHAI_SSENSE_API_KEY} # From .env
    restart: always

# Implicit Dockerfile content for each service (if you were to create them manually):
# api1/Dockerfile:
# FROM python:3.9-slim-buster
# WORKDIR /app
# COPY requirements.txt .
# RUN pip install -r requirements.txt
# COPY . .
# EXPOSE 5000
# CMD ["python", "app.py"]

# api2/Dockerfile:
# FROM python:3.9-slim-buster
# WORKDIR /app
# COPY requirements.txt .
# RUN pip install -r requirements.txt
# COPY . .
# EXPOSE 5001
# CMD ["python", "app.py"]